const debts = [
  {
    Creditor: "Dynazzy",
    Balance: "$8488.06",
    Min_Payment: "$375.77",
    APR: 0.07,
    Debt_Type: "Student Loan",
    Credit_Type: "Installment",
    Status: "Deferred",
    Autopay: false,
  },
  {
    Creditor: "Edgewire",
    Balance: "$874.95",
    Min_Payment: "$204.19",
    APR: 0.0,
    Debt_Type: "Medical Debt",
    Credit_Type: "Installment",
    Status: "Collectitons",
    Autopay: false,
  },
  {
    Creditor: "Capital One",
    Balance: "$6830.66",
    Credit_Limit: "$12000",
    Min_Payment: "$158.31",
    APR: 0.06,
    Debt_Type: "Credit Card",
    Credit_Type: "Revolving",
    Status: "Behind",
    Autopay: false,
  },
  {
    Creditor: "Rocket Mortgage",
    Balance: "$299841.10",
    Min_Payment: "$2253.11",
    APR: 0.04,
    Debt_Type: "Mortgage",
    Credit_Type: "Installment",
    Status: "Current",
    Autopay: true,
  },
  {
    Creditor: "Pixonyx",
    Balance: "$3122.34",
    Credit_Limit: "$8000.00",
    Min_Payment: "$82.64",
    APR: 0.18,
    Debt_Type: "Credit Card",
    Credit_Type: "Revolving",
    Status: "Behind",
    Autopay: false,
  },
  {
    Creditor: "Blognation",
    Balance: "$7140.88",
    Min_Payment: "$1173.70",
    APR: 0.15,
    Debt_Type: "Auto Loan",
    Credit_Type: "Installment",
    Status: "Collections",
    Autopay: true,
  },
  {
    Creditor: "Debtfeed",
    Balance: "$3061.71",
    Min_Payment: "$283.55",
    APR: 0.33,
    Debt_Type: "Personal Loan",
    Credit_Type: "Installment",
    Status: "Collections",
    Autopay: true,
  },
  {
    Creditor: "Flipopia",
    Balance: "$2293.89",
    Credit_Limit: "$20000.00",
    Min_Payment: "$76.89",
    APR: 0.18,
    Debt_Type: "Credit Card",
    Credit_Type: "Revolving",
    Status: "Current",
    Autopay: true,
  },
  {
    Creditor: "Fletcher Jones",
    Balance: "$19340.84",
    Min_Payment: "$492.29",
    APR: 0.08,
    Debt_Type: "Auto Loan",
    Credit_Type: "Installment",
    Status: "Current",
    Autopay: true,
  },
  {
    Creditor: "Yakitri",
    Balance: "$3500.00",
    Min_Payment: "$500",
    APR: 0,
    Debt_Type: "Personal Loan",
    Credit_Type: "Installment",
    Status: "Current",
    Autopay: false,
  },
  {
    Creditor: "Bank of America",
    Balance: "$873.07",
    Credit_Limit: "$5000.00",
    Min_Payment: "$54.43",
    APR: 0.23,
    Debt_Type: "Credit Card",
    Credit_Type: "Revolving",
    Status: "Current",
    Autopay: true,
  },
  {
    Creditor: "Home Depot",
    Balance: "$924.54",
    Credit_Limit: "$4000.00",
    Min_Payment: "$159.58",
    APR: 0.13,
    Debt_Type: "Credit Card",
    Credit_Type: "Revolving",
    Status: "Current",
    Autopay: true,
  },
  {
    Creditor: "Nelnet",
    Balance: "$6880.58",
    Min_Payment: "$553.08",
    APR: 0.05,
    Debt_Type: "Student Loan",
    Credit_Type: "Installment",
    Status: "Deferred",
    Autopay: false,
  },
  {
    Creditor: "Rhynyx Motorcycles",
    Balance: "$6283.90",
    Min_Payment: "$490.13",
    APR: 0.17,
    Debt_Type: "Auto Loan",
    Credit_Type: "Installment",
    Status: "Current",
    Autopay: true,
  },
];

export default debts;
