const transactions = 
[{
    "id": 1,
    "Date": "03/24/2022",
    "amount": "$73.86",
    "Description": "Health",
    "Item_Category": "Bills",
    "Card_Last_four": "3333",
    "Merchant": "Zoonoodle"
  }, {
    "id": 2,
    "Date": "09/27/2022",
    "amount": "$253.26",
    "Description": "Baby",
    "Item_Category": "Debt",
    "Card_Last_four": "0000",
    "Merchant": "Einti"
  }, {
    "id": 3,
    "Date": "11/20/2022",
    "amount": "$987.50",
    "Description": "Jewelry",
    "Item_Category": "Variable",
    "Card_Last_four": "9876",
    "Merchant": "Fiveclub"
  }, {
    "id": 4,
    "Date": "11/11/2022",
    "amount": "$622.61",
    "Description": "Toys",
    "Item_Category": "Subscription",
    "Card_Last_four": "9876",
    "Merchant": "Topicshots"
  }, {
    "id": 5,
    "Date": "08/11/2022",
    "amount": "$166.60",
    "Description": "Home",
    "Item_Category": "Debt",
    "Card_Last_four": "0000",
    "Merchant": "Meemm"
  }, {
    "id": 6,
    "Date": "07/13/2022",
    "amount": "$320.24",
    "Description": "Electronics",
    "Item_Category": "Debt",
    "Card_Last_four": "9876",
    "Merchant": "Riffwire"
  }, {
    "id": 7,
    "Date": "06/24/2022",
    "amount": "$319.46",
    "Description": "Outdoors",
    "Item_Category": null,
    "Card_Last_four": "0000",
    "Merchant": "Dazzlesphere"
  }, {
    "id": 8,
    "Date": "03/05/2023",
    "amount": "$556.38",
    "Description": "Toys",
    "Item_Category": "Bills",
    "Card_Last_four": "1122",
    "Merchant": "Thoughtstorm"
  }, {
    "id": 9,
    "Date": "07/24/2022",
    "amount": "$15.87",
    "Description": "Baby",
    "Item_Category": null,
    "Card_Last_four": "3333",
    "Merchant": "Plajo"
  }, {
    "id": 10,
    "Date": "03/03/2023",
    "amount": "$461.06",
    "Description": "Automotive",
    "Item_Category": null,
    "Card_Last_four": "3333",
    "Merchant": "Gabcube"
  }, {
    "id": 11,
    "Date": "05/30/2022",
    "amount": "$641.25",
    "Description": "Jewelry",
    "Item_Category": null,
    "Card_Last_four": "1122",
    "Merchant": "Eadel"
  }, {
    "id": 12,
    "Date": "02/25/2023",
    "amount": "$253.39",
    "Description": "Industrial",
    "Item_Category": "Debt",
    "Card_Last_four": "3333",
    "Merchant": "Brainsphere"
  }, {
    "id": 13,
    "Date": "09/20/2022",
    "amount": "$261.07",
    "Description": "Sports",
    "Item_Category": null,
    "Card_Last_four": "0000",
    "Merchant": "Minyx"
  }, {
    "id": 14,
    "Date": "07/01/2022",
    "amount": "$268.36",
    "Description": "Garden",
    "Item_Category": null,
    "Card_Last_four": "1122",
    "Merchant": "Feedfire"
  }, {
    "id": 15,
    "Date": "12/28/2022",
    "amount": "$355.72",
    "Description": "Outdoors",
    "Item_Category": "Debt",
    "Card_Last_four": "1122",
    "Merchant": "Quire"
  }, {
    "id": 16,
    "Date": "08/16/2022",
    "amount": "$58.41",
    "Description": "Games",
    "Item_Category": null,
    "Card_Last_four": "9876",
    "Merchant": "Browseblab"
  }, {
    "id": 17,
    "Date": "07/15/2022",
    "amount": "$93.92",
    "Description": "Toys",
    "Item_Category": "Subscription",
    "Card_Last_four": "1122",
    "Merchant": "Devpulse"
  }, {
    "id": 18,
    "Date": "03/18/2022",
    "amount": "$958.85",
    "Description": "Beauty",
    "Item_Category": "Variable",
    "Card_Last_four": "3333",
    "Merchant": "Quimm"
  }, {
    "id": 19,
    "Date": "09/07/2022",
    "amount": "$201.81",
    "Description": "Home",
    "Item_Category": "Bills",
    "Card_Last_four": "0000",
    "Merchant": "Jetpulse"
  }, {
    "id": 20,
    "Date": "06/06/2022",
    "amount": "$836.30",
    "Description": "Kids",
    "Item_Category": "Subscription",
    "Card_Last_four": "9876",
    "Merchant": "Twimbo"
  }, {
    "id": 21,
    "Date": "11/10/2022",
    "amount": "$748.28",
    "Description": "Health",
    "Item_Category": "Debt",
    "Card_Last_four": "3333",
    "Merchant": "Dynabox"
  }, {
    "id": 22,
    "Date": "10/03/2022",
    "amount": "$322.99",
    "Description": "Home",
    "Item_Category": null,
    "Card_Last_four": "9876",
    "Merchant": "Meembee"
  }, {
    "id": 23,
    "Date": "04/21/2022",
    "amount": "$869.54",
    "Description": "Kids",
    "Item_Category": null,
    "Card_Last_four": "9876",
    "Merchant": "Shufflester"
  }, {
    "id": 24,
    "Date": "04/23/2022",
    "amount": "$733.71",
    "Description": "Automotive",
    "Item_Category": null,
    "Card_Last_four": "9876",
    "Merchant": "Yacero"
  }, {
    "id": 25,
    "Date": "08/19/2022",
    "amount": "$405.08",
    "Description": "Books",
    "Item_Category": "Subscription",
    "Card_Last_four": "1122",
    "Merchant": "Linktype"
  }, {
    "id": 26,
    "Date": "12/14/2022",
    "amount": "$368.39",
    "Description": "Outdoors",
    "Item_Category": null,
    "Card_Last_four": "0000",
    "Merchant": "Browsebug"
  }, {
    "id": 27,
    "Date": "01/24/2023",
    "amount": "$206.73",
    "Description": "Books",
    "Item_Category": "Bills",
    "Card_Last_four": "1122",
    "Merchant": "Skimia"
  }, {
    "id": 28,
    "Date": "03/22/2023",
    "amount": "$985.79",
    "Description": "Clothing",
    "Item_Category": null,
    "Card_Last_four": "9876",
    "Merchant": "Tazz"
  }, {
    "id": 29,
    "Date": "10/24/2022",
    "amount": "$655.94",
    "Description": "Health",
    "Item_Category": "Bills",
    "Card_Last_four": "3333",
    "Merchant": "Fadeo"
  }, {
    "id": 30,
    "Date": "05/06/2022",
    "amount": "$268.19",
    "Description": "Toys",
    "Item_Category": "Variable",
    "Card_Last_four": "0000",
    "Merchant": "Thoughtbeat"
  }, {
    "id": 31,
    "Date": "10/26/2022",
    "amount": "$71.62",
    "Description": "Garden",
    "Item_Category": "Variable",
    "Card_Last_four": "9876",
    "Merchant": "Twiyo"
  }, {
    "id": 32,
    "Date": "04/21/2022",
    "amount": "$121.18",
    "Description": "Sports",
    "Item_Category": "Bills",
    "Card_Last_four": "3333",
    "Merchant": "Livetube"
  }, {
    "id": 33,
    "Date": "11/15/2022",
    "amount": "$265.42",
    "Description": "Industrial",
    "Item_Category": "Debt",
    "Card_Last_four": "0000",
    "Merchant": "Gigazoom"
  }, {
    "id": 34,
    "Date": "04/03/2022",
    "amount": "$924.21",
    "Description": "Grocery",
    "Item_Category": "Subscription",
    "Card_Last_four": "1122",
    "Merchant": "Shufflebeat"
  }, {
    "id": 35,
    "Date": "06/20/2022",
    "amount": "$918.12",
    "Description": "Computers",
    "Item_Category": null,
    "Card_Last_four": "1122",
    "Merchant": "Agimba"
  }, {
    "id": 36,
    "Date": "12/27/2022",
    "amount": "$738.26",
    "Description": "Automotive",
    "Item_Category": "Bills",
    "Card_Last_four": "3333",
    "Merchant": "Photobean"
  }, {
    "id": 37,
    "Date": "08/13/2022",
    "amount": "$167.59",
    "Description": "Garden",
    "Item_Category": "Subscription",
    "Card_Last_four": "9876",
    "Merchant": "Skilith"
  }, {
    "id": 38,
    "Date": "03/04/2023",
    "amount": "$978.13",
    "Description": "Sports",
    "Item_Category": "Debt",
    "Card_Last_four": "0000",
    "Merchant": "Wikizz"
  }, {
    "id": 39,
    "Date": "04/27/2022",
    "amount": "$506.22",
    "Description": "Beauty",
    "Item_Category": "Bills",
    "Card_Last_four": "3333",
    "Merchant": "Trunyx"
  }, {
    "id": 40,
    "Date": "05/29/2022",
    "amount": "$397.83",
    "Description": "Garden",
    "Item_Category": null,
    "Card_Last_four": "0000",
    "Merchant": "Agimba"
  }, {
    "id": 41,
    "Date": "03/24/2023",
    "amount": "$544.06",
    "Description": "Automotive",
    "Item_Category": null,
    "Card_Last_four": "1122",
    "Merchant": "Avamba"
  }, {
    "id": 42,
    "Date": "05/07/2022",
    "amount": "$236.73",
    "Description": "Outdoors",
    "Item_Category": null,
    "Card_Last_four": "0000",
    "Merchant": "Shufflester"
  }, {
    "id": 43,
    "Date": "03/05/2023",
    "amount": "$752.18",
    "Description": "Health",
    "Item_Category": "Variable",
    "Card_Last_four": "3333",
    "Merchant": "Blogpad"
  }, {
    "id": 44,
    "Date": "10/29/2022",
    "amount": "$571.94",
    "Description": "Shoes",
    "Item_Category": "Debt",
    "Card_Last_four": "1122",
    "Merchant": "Brainverse"
  }, {
    "id": 45,
    "Date": "03/29/2022",
    "amount": "$856.83",
    "Description": "Baby",
    "Item_Category": "Variable",
    "Card_Last_four": "3333",
    "Merchant": "Agivu"
  }, {
    "id": 46,
    "Date": "12/31/2022",
    "amount": "$451.14",
    "Description": "Movies",
    "Item_Category": "Bills",
    "Card_Last_four": "0000",
    "Merchant": "Pixope"
  }, {
    "id": 47,
    "Date": "10/31/2022",
    "amount": "$430.04",
    "Description": "Garden",
    "Item_Category": "Bills",
    "Card_Last_four": "0000",
    "Merchant": "Gigabox"
  }, {
    "id": 48,
    "Date": "10/22/2022",
    "amount": "$794.47",
    "Description": "Home",
    "Item_Category": null,
    "Card_Last_four": "0000",
    "Merchant": "Jaxworks"
  }, {
    "id": 49,
    "Date": "05/13/2022",
    "amount": "$284.47",
    "Description": "Tools",
    "Item_Category": "Debt",
    "Card_Last_four": "1122",
    "Merchant": "Twiyo"
  }, {
    "id": 50,
    "Date": "05/26/2022",
    "amount": "$257.42",
    "Description": "Electronics",
    "Item_Category": "Variable",
    "Card_Last_four": "9876",
    "Merchant": "Buzzster"
  }]

  export default transactions