export const users = [
  {
    firstname: "Adrian",
    lastname: "Smith",
    company: "Southwest Airlines",
    position: "Software Engineer",
    personalemail: "adrianiscool@gmail.com",
    workemail: "adrian.smith@southwest.com",
    phone: "702-555-1234",
    profilephotosource: "",
    ssn: "",
    address: {
      address1: "123 Main St.",
      address2: "",
      zipcode: "89111",
      city: "Las Vegas",
      state: "NV",
    },
  },
  {
    firstname: "Shanice",
    lastname: "Johnson",
    company: "Southwest Airlines",
    position: "Chief People Officer",
    personalemail: "alwayshelping@gmail.com",
    workemail: "shanice.johnson@southwest.com",
    phone: "702-123-4567",
    profilephotosource: "darius-j-smith",
    ssn: "",
    address: {
      address1: "555 Corporate cir.",
      address2: "",
      zipcode: "89333",
      city: "Las Vegas",
      state: "NV",
    },
  },
  {
    firstname: "Nathan",
    lastname: "Hemmingway",
    company: "Southwest Airlines",
    position: "Marketing Director",
    personalemail: "natehem50@gmail.com",
    workemail: "nathan.hemmingway@southwest.com",
    phone: "702-765-4321",
    profilephotosource: "",
    ssn: "",
    address: {
      address1: "123 Photograph blvd.",
      address2: "",
      zipcode: "89222",
      city: "Las Vegas",
      state: "NV",
    },
  },
  {
    firstname: "Charles",
    lastname: "Lewis",
    company: "Southwest Airlines",
    position: "Sales Agent",
    personalemail: "clew3230@hotmail.com",
    workemail: "charles.lewis@southwest.com",
    phone: "323-555-7890",
    profilephotosource: "",
    ssn: "",
    address: {
      address1: "123 Photograph blvd.",
      address2: "",
      zipcode: "90210",
      city: "Los Angelos",
      state: "CA",
    },
  },
];
